[campaign]
    name = 'cpn_atlantic'
    dir = './'

[[experiments]]
    priority = 2
    name = "exp_002"            # if not given the epoch time is set instead, e.g exp_1555423461
    samples = 1                 # the number of times the experiment will run
    first_freq = 10000.0
    last_freq = 100000.0
    freq_step = 10000.0

    [experiments.signals]
        type = "gr_sine_gen"
        samp_rate = 250000.0
        pwm_freq = 1.0
        ncycles = 1000
        npulses = 1
        sig_amp = 1.0
        pre_padding = 0
        post_padding = 0
        # sig_freq = 1000.0


    [experiments.transmission]
        type = "gr_baseband_async_oii"
        amplitude_calibration1 = 3.7929649
        amplitude_calibration2 = 3.7929649
        duration = 250000
        tx_ip = "192.168.5.100"
        rx_ip1 = "192.168.5.100"
        rx_ip2 = "192.168.5.100"
        ch_tx = 1
        ch_rx1 = 1
        ch_rx2 = 2
        samp_rate = 250000.0




[[experiments]]
    priority = 1
    name = "exp_001"            # if not given the epoch time is set instead, e.g exp_1555423461
    samples = 1                 # the number of times the experiment will run
    first_freq = 10000.0
    last_freq = 100000.0
    freq_step = 10000.0

    [experiments.signals]
        type = "gr_sine_gen"
        samp_rate = 250000.0
        pwm_freq = 1.0
        ncycles = 1000
        npulses = 1
        sig_amp = 1.0
        pre_padding = 0
        post_padding = 0
        # sig_freq = 1000.0


    [experiments.transmission]
        type = "gr_baseband_async_oii"
        amplitude_calibration1 = 3.7929649
        amplitude_calibration2 = 3.7929649
        duration = 250000
        tx_ip = "192.168.5.100"
        rx_ip1 = "192.168.5.100"
        rx_ip2 = "192.168.5.100"
        ch_tx = 1
        ch_rx1 = 1
        ch_rx2 = 2
        samp_rate = 250000.0
