#!/usr/bin/env python
""" """

import os
import sys
import datetime
import numpy as np

from dsp.transmission_gr38.gr_bandpass_async_oii import gr_bandpass_async_oii
from dsp.transmission_gr38.gr_bandpass_async_oii import main
from optparse import OptionParser


sig_in = sys.argv[1]                        # -
duration = int(sys.argv[2])                 # 0 (auto)
amplitude_calibration = float(sys.argv[3])  # 1.
center_freq = float(sys.argv[4])            # 80000.
dtype = sys.argv[5]                         # 'float32', 'complex64'
samp_rate = float(sys.argv[6])              # 250000.
tx_ip = str(sys.argv[7])                    # 192.168.5.100
rx_ip = str(sys.argv[8])                    # 192.168.5.101


date = str(datetime.datetime.now()).split('.')[0].replace(' ', '_')

if duration == 0:
    with open(sig_in, 'rb') as fd:
        duration = len(np.fromfile(fd, dtype=dtype))

out1_name = date + '_' + sig_in.rsplit('.', 1)[0].rsplit('/')[-1] + '_r' + str(samp_rate) + '_d' + str(duration) + '_ch1.dat'
out2_name = date + '_' + sig_in.rsplit('.', 1)[0].rsplit('/')[-1] + '_r' + str(samp_rate) + '_d' + str(duration) + '_ch2.dat'

# center_freq = 80000.

tb = gr_bandpass_async_oii(
    amplitude_calibration1=amplitude_calibration,
    amplitude_calibration2=amplitude_calibration,
    duration=duration,
    rx_ip1=rx_ip,
    rx_ip2=rx_ip,
    tx_ip=tx_ip,
    samp_rate=samp_rate,
    sig_in=sig_in,
    sig_out1=out1_name,
    sig_out2=out2_name,
    center_freq=center_freq,
    ch_rx1=1001,
    ch_rx2=1002,
    ch_tx=1001,
)
tb.start()
tb.wait()