#!/usr/bin/env python
# -*- coding: utf-8 -*-
""" """

import platform
if platform.system() == 'Darwin':
    import matplotlib
    matplotlib.use('TkAgg')

import numpy as np
from optparse import OptionParser
import matplotlib.pyplot as plt
import sys

def argument_parser():
    parser = OptionParser(usage="%prog: [options]")

    parser.add_option(
        "-r", "--samp_rate", dest="samp_rate", type="float", default=250000.,
        help="Set sample rate [default=%default]")

    parser.add_option(
        "-i", "--input-signals", dest="input_signals", type="string", default='./in.dat',
        help="Set input signals list [default=%default]")

    parser.add_option(
        "-d", "--data-type", dest="data_type", type="string", default='float32',
        help="Set data type, e.g float32, complex64 [default=%default]")


    return parser

# Get parameters
in_params, _ = argument_parser().parse_args()

# Sample rate
fs = in_params.samp_rate
data_type = in_params.data_type
input_signals = in_params.input_signals

# Data type
allowed_data_types = (
    'float32',
    'complex64',
)
if data_type not in allowed_data_types:
    print('[E] Data type `{}` not allowed.'.format(data_type))
    sys.exit(1)

for sig in input_signals.split(','):
    f = open(sig, 'rb')
    data = np.fromfile(f, dtype=data_type)
    t = np.arange(len(data))/fs

    if data_type == 'complex64':
        plt.plot(t, data.real)
        plt.plot(t, data.imag)
    elif data_type == 'float32':
        plt.plot(t, data)
plt.show()
